name: "jarrett"
description: "Development Blog"

author: "Jarrett Harris"

url: "http://jarrettch.github.io/blog2"
baseurl: "/blog2"

markdown: rdiscount
permalink: :year/:month/:title.html
pygments: true

# Google Analytics
# ga_domain: m3xm.github.io
# ga_tracking_id: UA-47727049-1
